import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationBar from "../components/NavigationBar";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next Appp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavigationBar></NavigationBar>
          {children}
          <SpeedInsights></SpeedInsights>
        </Providers>
      </body>
    </html>
  );
}
